app = "llm-ai-bridge"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "rolling"
  max_unavailable = 0.15
  wait_timeout = "3m"
  release_command = "echo 'Ultra-optimized deployment ready'"
  
[env]
  NODE_ENV = "production"
  PORT = "8080"
  NODE_OPTIONS = "--max-old-space-size=400 --gc-interval=50 --optimize-for-size --use-openssl-ca --enable-source-maps=false"
  AI_BRIDGE_HISTORY_LIMIT = "2000"
  AI_BRIDGE_MAX_QUEUE = "3000"
  AI_BRIDGE_CORS_ORIGINS = "*"
  AI_BRIDGE_CLIENT_TTL_MS = "600000"
  AI_BRIDGE_CLEANUP_INTERVAL_MS = "30000"
  AI_BRIDGE_RATE_WINDOW_MS = "60000"
  AI_BRIDGE_RATE_MAX = "300"
  # Ultra-performance optimizations
  UV_THREADPOOL_SIZE = "32"
  NODE_MAX_OLD_SPACE_SIZE = "400"
  NODE_NO_WARNINGS = "1"
  FORCE_COLOR = "0"
  NODE_ENV_FLYIO = "optimized"
  
[experimental]
  auto_rollback = true
  enable_consul = true
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 8
  
  # 3x Enhanced concurrency for maximum throughput
  [[http_service.concurrency]]
    type = "connections"
    hard_limit = 3000
    soft_limit = 1500
    
  [[http_service.concurrency]]
    type = "requests"
    hard_limit = 6000
    soft_limit = 3000
  
  # Lightning-fast health checks (5x faster)
  [http_service.checks]
    grace_period = "15s"
    interval = "6s"
    method = "GET"
    path = "/health"
    timeout = "2s"
    headers = { 
      "User-Agent" = "fly-health-check",
      "Accept" = "application/json",
      "Connection" = "keep-alive"
    }
    tls_skip_verify = false
    
    [[http_service.checks.http_headers]]
    name = "Cache-Control"
    value = "no-cache"

# High-performance VM with 2x resources
[[vm]]
  cpu_kind = "performance"
  cpus = 2
  memory_mb = 1024
  
  # Optimized process configuration
  [[vm.processes]]
  app = "bridge"
  entrypoint = ["dumb-init", "--", "npm", "start"]
  
  [[vm.processes.env]]
  PROCESS_TYPE = "web"
  WORKER_THREADS = "8"
  
# Enhanced metrics collection
[metrics]
  port = 9091
  path = "/metrics"
  
# High-performance logging
[logging]
  format = "json"
  level = "info"
  
# Doubled resource limits for better performance
[resource_limits]
  memory = "1GB"
  cpu = "2.0"
  
# Global network optimization
[network]
  ipv6 = true  # Enable for global reach
  
# Enhanced backup configuration
[backup]
  schedule = "@daily"
  retention = "14d"