app = 'llm-framework-prod'
primary_region = 'dfw'
kill_signal = 'SIGINT'
kill_timeout = '10s'

[experimental]
  auto_rollback = true

[build]

[env]
  NODE_ENV = 'production'
  PORT = '8080'
  DASHBOARD_PORT = '8081'
  MCP_PORT = '3001'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 800

[[http_service.checks]]
  interval = '30s'
  timeout = '5s'
  grace_period = '15s'
  method = 'get'
  path = '/healthz'

[processes]
  app = "node server-enhanced.js"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[deploy]
  release_command = 'npm run build || echo Build attempted'
  strategy = 'canary'