name: llm-ai-bridge
description: LLM AI Bridge with Nitric Cloud-Native Optimization

services:
  - match: "src/nitric/**/*.js"
    start: node $SERVICE_PATH
    type: default
  - match: "src/nitric/**/*.ts"  
    start: npx tsx $SERVICE_PATH
    type: default

websites:
  - name: llm-website
    basedir: website
    index: index.html
    error: 404.html
    custom_domain: www.scarmonit.com
    build:
      command: npm run build:website
      output: ./website/dist
    dev:
      command: npm run dev:website -- --port 4322
      url: http://localhost:4322

providers:
  - nitric/aws@latest
  - nitric/azure@latest
  - nitric/gcp@latest

preview:
  - nitric/docker@latest

# Performance optimization settings
config:
  cdn:
    enabled: true
    cache_policy: "max-age=31536000"
  ssl:
    enabled: true
    redirect_http: true
  compression:
    enabled: true
    types: ["text/html", "text/css", "application/javascript", "application/json"]
  security:
    headers:
      x-frame-options: "DENY"
      x-content-type-options: "nosniff"
      referrer-policy: "strict-origin-when-cross-origin"
      content-security-policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"