apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-framework
  labels:
    app: llm-framework
    version: "2.0.0"
    optimization: advanced
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: llm-framework
  template:
    metadata:
      labels:
        app: llm-framework
        version: "2.0.0"
        optimization: advanced
    spec:
      serviceAccountName: llm-framework-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: llm-framework
        image: ghcr.io/scarmonit-creator/llm-framework:latest
        ports:
        - containerPort: 8080
          name: api
        - containerPort: 8081
          name: metrics
        env:
        - name: NODE_ENV
          value: "production"
        - name: ENABLE_MEMORY_OPTIMIZATION
          value: "true"
        - name: ENABLE_CACHE_OPTIMIZATION
          value: "true"
        - name: ENABLE_SECURITY_HARDENING
          value: "true"
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: llm-framework-secrets
              key: encryption-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        - name: cache-volume
          mountPath: /app/.cache
        - name: secure-storage
          mountPath: /app/.secure-storage
      volumes:
      - name: cache-volume
        emptyDir:
          sizeLimit: 1Gi
      - name: secure-storage
        emptyDir:
          sizeLimit: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: llm-framework-service
  labels:
    app: llm-framework
spec:
  selector:
    app: llm-framework
  ports:
  - name: api
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: llm-framework-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: llm-framework
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60