name: Codestral AI Optimization

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at midnight

jobs:
  optimize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Codestral AI Optimization
        run: npm run optimize:codestral
        env:
          CODESTRAL_API_KEY: ${{ secrets.CODESTRAL_API_KEY }}

      - name: Upload optimization report
        uses: actions/upload-artifact@v4
        with:
          name: codestral-optimization-report
          path: codestral-optimization-report.json
          retention-days: 30

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('codestral-optimization-report.json', 'utf8'));
            const comment = `## 🤖 Codestral AI Optimization Report

            - **Files Analyzed:** ${report.summary.filesAnalyzed}
            - **Issues Found:** ${report.summary.issuesFound}
            - **Optimizations Applied:** ${report.summary.optimizationsApplied}
            - **Performance Gain:** ${report.summary.performanceGain}
            - **Duration:** ${report.duration}

            Full report available in workflow artifacts.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
