name: Update package-lock.json

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    paths:
      - 'package.json'

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'
      
      - name: Remove old lock file
        run: rm -f package-lock.json
      
      - name: Generate new lock file
        run: npm install --package-lock-only
      
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected in package-lock.json"
            git status --short
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi
      
      - name: Create Pull Request for lockfile update
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: Update package-lock.json [skip ci]'
          title: 'chore: Update package-lock.json'
          body: |
            ## Package Lock Update
            
            This PR updates the `package-lock.json` file to synchronize with changes in `package.json`.
            
            ### Changes
            - Updated package-lock.json based on package.json modifications
            
            **Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            This PR was created to comply with branch protection rules that require changes via pull request.
          branch: update-lockfile-${{ github.run_id }}
          base: main
          delete-branch: true
          labels: |
            automated
            lockfile
            maintenance
