name: Update package-lock.json

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    paths:
      - 'package.json'

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Remove old lock file
        run: rm -f package-lock.json
      
      - name: Generate new lock file
        run: npm install --package-lock-only
      
      - name: Commit and push lock file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add package-lock.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: Update package-lock.json [skip ci]" && git push)
        continue-on-error: false
